# Generated by Django 4.1 on 2022-12-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_quiz_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='contenido',
            field=models.JSONField(),
        ),
    ]
